name: Frontend CI CD workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ] # Triggers the workflow on push events but only for the "master" branch
  pull_request: # Triggers the workflow on pull request events for any branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master'}} 
    steps:
      - name: say hello
        run: echo ${{ github.ref }} 

  # This is a job called "deploy" 
  build_deploy:
    needs: build
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/master'
    steps:
      - name: say hello
        run: echo "hello from build_deploy"