name: Frontend CI CD workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Triggers the workflow on push events but only for the "master" branch
  pull_request: # Triggers the workflow on pull request events for any branch
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    steps:
      - name: show branch name that initiated the workflow
        run: echo 'branch name:' ${{ github.ref }} 
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: get sources
        uses: actions/checkout@v3
        
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: install node modules
        working-directory: .      
        run: npm install

      - name: compile
        working-directory: .        
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist
          
  # This is a job called "deploy" 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master'}} # if the branch that we commit to is master then we run "deploy"
    steps:
      - name: say hello
        run: echo "hello from build_deploy"